### ISSUE TITLE
switch setup.py to pyproject.toml 

### ISSUE THREAD

**Issue by baggiponte** [huggingface/quanto#123]
Ciao! Great job with quanto, can't wait to play with it. Would like to propose to switch the project config to  `pyproject.toml` completely: it's the new standard for python packaging and I already implemented that for HF datatrove [here](https://github.com/huggingface/datatrove/pull/59). There are some references on why it might be optimal to make the switch [here](https://github.com/huggingface/datatrove/issues/54#issue-2091467367).

**Comment by dacorvo** [comment]
@baggiponte thank you for your feedback.
As you can see in the commit below, the only reason there is a `setup.py` is because of an issue when parsing metadata using setuptools:

https://github.com/huggingface/quanto/commit/b9757456fb5a90302fd0740511a05ff6369b8f17

**Comment by baggiponte** [comment]
Thanks for the reply! The metadata that was not properly parsed was the URLs? It did not display properly on PyPI?

**Comment by dacorvo** [comment]
Yes (the previous commit).

**Comment by baggiponte** [comment]
Ciao @dacorvo, sorry for the late reply. I opened a draft PR to provide a possible solution and see if you could reproduce the bug you mention about the commit with this setup.

(What a keen eye! That was my previous employer and I never asked. Though I am looking for one now!)
