### ISSUE TITLE
Is there a plan to add more flexible methods for setting quantization configs

### ISSUE THREAD

**Issue by shuokay** [huggingface/quanto#124]
There are some scenarios require more flexible and powerful methods for setting quantization configs, for examples:

1. Setting different quantization bits for the same type of operator: Taking conv as an example, in the first few layers of the model, it is usually necessary to set conv to qint16 to improve model accuracy, and then set it to qint8 to improve model performance
2. Operator fusion: In the scenario of conv+bn, it is usually necessary to remove the conv fused with bn to improve deployment performance on NPUs
3. Heuristic setting of quantization configuration, such as OpA ->OpB. If OpB can be both int8 input and int16 input, then it is best for OpB's input type to be consistent with OpA's input type to avoid quantization and improve performance

Most of the above features require the compute graph(aka. fx.Graph), but the README highlight that quanto is based on the eager mode. May I ask how the above problems were considered?

**Comment by dacorvo** [comment]
> Setting different quantization bits for the same type of operator: Taking conv as an example, in the first few layers of the model, it is usually necessary to set conv to qint16 to improve model accuracy, and then set it to qint8 to improve model performance
You can do that already: just call quantize multiple times on the specified layers instead of calling it once for the whole model.

> Operator fusion: In the scenario of conv+bn, it is usually necessary to remove the conv fused with bn to improve deployment performance on NPUs

quanto is a quantization toolkit, no more, no less. Graph rewriting is out-of-scope, as we want to avoid "mission-creep".
But we hope quanto is versatile enough to be combined with other tools. 

> Heuristic setting of quantization configuration, such as OpA ->OpB. If OpB can be both int8 input and int16 input, then it is best for OpB's input type to be consistent with OpA's input type to avoid quantization and improve performance

This already supported: https://github.com/huggingface/quanto/blob/9192ef865fe3dfe05bc867a6aa2f1e2276e7d6f8/quanto/calibrate.py#L30.

**Comment by dacorvo** [comment]
FYI, I did not need to use the fx graph because I used a custom DispatchMode to "observe" the actual graph myself directly.

**Comment by shuokay** [comment]
@dacorvo To my knowledge, with the DispatchMode, operators can only access info of other operators exactly before and after them, but not larger scope information(If wrong, please feel free to correct me). However, for the performance optimization (e.g. to avoid heavy requantization), sometimes access to larger scope information is necessary."

**Comment by dacorvo** [comment]
@shuokay yes you're right, but it is a bit smarter than that thanks to the tensor subclasses: I can track where they come from, which allows for more global heuristics.
Anyway, this is for straightforward optimization: advanced algorithms should use pattern matching an graph traversal using dynamo. I am not so sure it should be part of quanto though.

**Comment by shuokay** [comment]
@dacorvo  I have worked on an quantization framework that based on fx.Graph before,  it worked well in most cases, but it is hard for users to debug if the model accuracy is not as expected, so I guess quanto is a good try. What's more, if we make quanto compatible with dynamo which I think is one of quanto's targets, it is not very hard to add support for graph rewrite.
