### ISSUE TITLE
Performance of quanto quants vs bnb, AWQ, GPTQ, GGML ?

### ISSUE THREAD

**Issue by nnethercott** [huggingface/quanto#129]
I was wondering if there were any comparisons done looking at the speed and ppl of `quanto` quantizations with respect to the other quantization techniques out there.

**Comment by dacorvo** [comment]
I have modified the benchmark tools to allow comparisons: https://github.com/huggingface/quanto/pull/128.
There are some numbers in the pull-request, but I don't want to make an explicit comparison page because the point is not to create a competition but to foster innovation.
