### ISSUE TITLE
Introduce optimizers

### ISSUE THREAD

**Issue by dacorvo** [huggingface/quanto#131]
By default quanto implements a simple absmax algorithm to evaluate the scale and zero-point to be used when quantizing QTensor and QBitsTensor. A refactoring is required in order to allow different algorithms.

1. Modify the QBitsTensor AffineQuantizer to accept directly scale and zero-point as parameters.

The code to evaluate the scale group-wise should be moved to absmax_scale, and the zero-point evaluated in QBitsTensor.quantize.

2. Introduce a new AffineOptimizer abstract base class that takes the following parameters in its call method:

- a source Tensor,
- a target qtype,
- an axis,
- a group_size.

This optimizer will return a scale and Zero-point.

3. Implement an AffineMaxOptimizer.

4. Use the AffineMaxOptimizer in QBitsTensor.quantize, QModuleMixin.qweights

**Comment by shuokay** [comment]
I want to proposal a discussion about whether we need to return zeropoint in the Optimizer.
1. If return the zeropoint in the Optimizer, the zeropoint is non-sense in symmetric quantization scheme, and we need to return zero tensor as the zeropoint, which will occupy memory. How, the LLMs are memory bottlenecked, It maybe better not return zeropoint in Optimizer and evaluate it when needed. 
2. But if we compute the zeropoint separately, it is not direct and clear and there are recomputations like `torch.min`

**Comment by dacorvo** [comment]
@shuokay agreed. I will create two abstract classes: one for symmetric optimizers, the other for affine ones.

**Comment by dacorvo** [comment]
@shuokay I understand you are interested in adding more optimizers: please wait until I implement this before starting any developments.

Here is my branch: https://github.com/huggingface/quanto/tree/optimizers

**Comment by dacorvo** [comment]
Implemented in #132
