### ISSUE TITLE
Dequantizing tensors using quanto

### ISSUE THREAD

**Issue by raunaks13** [huggingface/quanto#139]
I noticed the quantized models have these 4 additional features, for every weight in the original, e.g:
```
model.layers.0.mlp.down_proj.activation_qtype,
model.layers.0.mlp.down_proj.input_scale,
model.layers.0.mlp.down_proj.output_scale,
model.layers.0.mlp.down_proj.weight_qtype
```
I guess `qtype` refers to the quantized datatype, and `scale` probably refers to the scaling factor used during quantization? Although what is the difference between `input_scale` and `output scale`? Is it possible to recreate the exact original tensor using these values and the quantized weight?
If yes, then what would the formula be for the dequantization?

**Comment by shuokay** [comment]
>what is the difference between input_scale and output scale?

As the variable named, `input_scale` is the scale of input, and `output_scale` is the scale of the output for the operator

>Is it possible to recreate the exact original tensor using these values and the quantized weight?

original tensor: No, During quantization, the round operation is used,  and for round, it's not possible to uniquely determine the input based on the output.
quantized weight： Yes, if you have scale, weight quantization is somehow like: `clamp(round(weight / scale), qmin, qmax)` , you can refer to https://github.com/huggingface/quanto/blob/main/quanto/tensor/qtensor.py#L58-L62 for more infomation.

>what would the formula be for the dequantization?

Dequantization corresponds to quantization. For symmetric quantization, the dequantization is somehow like `scale * quantized_tensor`, refer to: https://github.com/huggingface/quanto/blob/main/quanto/tensor/qtensor.py#L76-L84

**Comment by raunaks13** [comment]
Thanks for your reply @shuokay .
When loading a mistral model I noticed that the `output_scale` and `input_scale` values were just tensors with the value 1, i.e. `tensor(1., device='cuda:0')`
This seems incorrect, since the model was quantized correctly. Is there a reason for this?
Here is the code I used:
```
seed = 1
model_id = "mistralai/Mistral-7B-Instruct-v0.2"
device = None
torch.manual_seed(seed)

if device is None:
    if torch.cuda.is_available():
        device = torch.device("cuda")
        print("Using cuda device")
    elif torch.backends.mps.is_available():
        device = torch.device("mps")
    else:
        device = torch.device("cpu")
else:
    device = torch.device(device)
    
weights = keyword_to_qtype(weights_type)
activations = keyword_to_qtype(activations_type)
dtype = torch.float32 if device.type == "cpu" else torch.float16
tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token_id = tokenizer.eos_token_id
tokenizer.padding_side = "left"
model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=dtype, low_cpu_mem_usage=True).to(device)

if weights is not None or activations is not None:
    print("Quantizing")
    start = time.time()
    quantize(model, weights=weights, activations=activations)
    # freeze(model)
    print(f"Finished: {time.time()-start:.2f}")
```
