### ISSUE TITLE
Question: If we have a model wrapped in another class, will that will work with the Calibration mode?

### ISSUE THREAD

**Issue by aryanmagoon** [huggingface/quanto#141]
I have a pytorch model for image resolution enhancement that I have wrapped inside of a helper class that I actually use to inference the model. As shown in the sample, we can use calibration mode in order to calibrate the model after quantization. Because I have the helper class, I use it like this: 

```py
from quanto.calibrate import *
with Calibration(momentum=0.9):
  for file in x:
    imageq = Image.open('images/' + file)
    imageq = np.array(imageq)
    final=upscale.enhance(imageq, outscale=4)
```

Where the function `enhance` actually inferences the model using `model(sample)`

Is this ok to do? After I quantize the model weights and activations, my model has seemed to stop working and only returns full black images and I'm not sure why. Additionally it's important to know that I only calibrated the model with about 102 images. Thank you for the help in advance.

**Comment by dacorvo** [comment]
You are using the calibration correctly (the context is precisely there to allow your kind of configuration where you don't actually call directly the model).
Quantizing a model can be frustrating, so I would recommend to go step by step.
Try first to quantize only the weights, and see if the quantized model gives good results.
Then, try also to quantize activations. There is a debug option to Calibrate that should give you a more verbose output.
