### ISSUE TITLE
Error when quantizing network and running calibration.

### ISSUE THREAD

**Issue by lambertsbennett** [huggingface/quanto#150]
I have a very simple network that consists of:

Conv2D -> BatchNorm2D -> ReLU -> MaxPool

A couple times and then a flatten layer with two linear layers. The last layer has a single output. This seems to cause an issue during quantization and raises the following error:

```
ValueError: Cannot quantize Tensor of shape torch.Size([1, 32]) along axis 0 of size 1
```

I bet this is a simple error, but I'm not sure what the issue is.

Thanks for the help.

**Comment by shuokay** [comment]
It seems that the output channel of Linear is 1, and quanto didn't support per-channel quantization on Tensor with "channel" size 1.

cc @dacorvo I think we can fix this by simply removing the check: https://github.com/huggingface/quanto/blob/main/quanto/tensor/quantizers/symmetric.py#L33-L34

**Comment by dacorvo** [comment]
It does not make sense to quantize a layer with only one output channel, especially the last one, as it will give terrible results, even in 8-bit.
Quantization is efficient only for large linear layers.

**Comment by lambertsbennett** [comment]
Ah ok, good to know. Thanks for the info!
