### ISSUE TITLE
Inference Speed of Quantized Model

### ISSUE THREAD

**Issue by mdatres** [huggingface/quanto#151]
Dear all, 

I am trying to quantize a resnet50 model on my dataset using quanto. I have followed the code provided in the example folder, but I have noticed that quantized model is slower than the floating-point counterpart. Indeed, this is the output of my 

> Best checkpoint has been loaded!
> 
> Test set evaluated in 9.70 s: Average loss: 0.2061, Accuracy: 2026/2201 (92%), MCC: 0.8214628100395203, F1: 0.9204906821250916
> 
> Calibrating ...
> 
> Test set evaluated in 50.60 s: Average loss: 0.0058, Accuracy: 6443/6869 (94%), MCC: 0.8815362453460693, F1: 0.9379822611808777
> 
> Model is calibrated!
> 
> Test set evaluated in 16.00 s: Average loss: 0.2380, Accuracy: 2007/2201 (91%), MCC: 0.8054866790771484, F1: 0.9118582606315613

I tried to run the script multiple times and the results are consistent with the one above. Do you have any idea what the cause of this behavior could be?

I can provide you the code (if it is needed), but unfortunately the dataset is private. 

Thanks in advance!
Max

**Comment by dacorvo** [comment]
The quantization has a cost, as explained in the [README](https://github.com/huggingface/quanto?tab=readme-ov-file#performances).

**Comment by dacorvo** [comment]
No, it can be used immediately, but mostly if you have device memory constraints (mostly for LLM).

**Comment by mdatres** [comment]
Sorry, I probably miss the point but what is the gain of using quantization if it is 2x slower than the floating point model? On one hand, the memory consumption is reduced but at the price of a slower inference phase, is it convenient?

Thanks, 
Max
