### ISSUE TITLE
Why does QTensor need both `__torch_function__` and `__torch_dispatch__` by design?

### ISSUE THREAD

**Issue by shuokay** [huggingface/quanto#156]
Hi @dacorvo ,
Torch provides the `__torch_function__` and `__torch_dispatch__` interfaces. According to the content from https://dev-discuss.pytorch.org/t/what-and-why-is-torch-dispatch/557 and https://github.com/albanD/subclass_zoo, `__torch_dispatch__` seems to attempt to provide more flexibility and functionality than `__torch_function__`. My question is, in quanto `QTensor`, why both `__torch_function__` and `__torch_dispatch__` interfaces are used simultaneously, Is it possible to use only one of them? If yes, what are the advantages of using both simultaneously? Can you tell how it was considered when designing `QTensor?```

**Comment by dacorvo** [comment]
The dispatch at the function level is to capture high-level functions that can benefit from operator fusion directly (typically `torch.nn.functional.linear`). The default dispatch at the ATEN level would miss that.
