### ISSUE TITLE
quantize() returns None with VGG19

### ISSUE THREAD

**Issue by jonahclarsen** [huggingface/quanto#157]
Hi there,

I was hoping to use quanto to make my Neural Style Transfer application use less VRAM, which depends on the VGG19 classification model. However, when I run the following code, quanto.quantize() seems to return None, as the last line prints "None":

```
import torchvision.models as models
import quanto

model = models.vgg19(pretrained=True)

model = quanto.quantize(model, weights=quanto.qint8, activations=quanto.qint8)
print(model)
```
I've tested and this happens on Mac, Windows, and WSL. I'm using torch 2.2.2, torchvision 0.17.2, and quanto 0.1.0. I could be missing something, thanks in advance!

**Comment by dacorvo** [comment]
@jonahclarsen the model is quantized 'in-place' (i.e. the original model is directly modified): this is why `quantize` returns `None`.

**Comment by IceWind233** [comment]
> Hi there,
> 
> I was hoping to use quanto to make my Neural Style Transfer application use less VRAM, which depends on the VGG19 classification model. However, when I run the following code, quanto.quantize() seems to return None, as the last line prints "None":
> 
> ```
> import torchvision.models as models
> import quanto
> 
> model = models.vgg19(pretrained=True)
> 
> model = quanto.quantize(model, weights=quanto.qint8, activations=quanto.qint8)
> print(model)
> ```
> 
> I've tested and this happens on Mac, Windows, and WSL. I'm using torch 2.2.2, torchvision 0.17.2, and quanto 0.1.0. I could be missing something, thanks in advance!

the ```quantize()``` does not have return value and the model you passed in is the quantized model

**Comment by jonahclarsen** [comment]
Oh of course! Silly me. Thanks!
