### ISSUE TITLE
VGG19 not using any less VRAM in qint8/qfloat8 than in fp16

### ISSUE THREAD

**Issue by jonahclarsen** [huggingface/quanto#159]
The readme says that memory will be "approximately divided by float bits / integer bits", so I expected quantizing a model in qint8/qfloat8 would use about 50% of the VRAM that's used when loading that model in fp16. However, it seems to use about the same.

I am on Windows, using Pytorch 2.2.2+cu118 and quanto 0.1.0.

Have I misunderstood something?

Code that demonstrates this (but also I can see in Task Manager when inferencing the model that quantizing with quanto doesn't affect VRAM usage):
```
import quanto, torch, torchvision

size = 2750 # with 8GB VRAM this works at 2750 but gives "CUDA out of memory" at 3000, no matter if half or quantized with quanto

model = torchvision.models.vgg19()
input_tensor = torch.ones([1, 3, size, size]).cuda()

if True: # Change this to False to change qint8 to fp16
    quanto_dtype = quanto.qint8 # Same problem no matter if this is qint8, qfloat8, qint4, qint2
    quanto.quantize(model, weights=quanto_dtype, activations=quanto_dtype)
    quanto.freeze(model)
else:
    model = model.half()
    input_tensor = input_tensor.half()

model = model.cuda()

output = model(input_tensor)
```

Note that with the latest Nvidia drivers, by default when VRAM is almost full, CUDA will start using system/CPU memory, so you won't be able to hit the "CUDA out of memory" error that I did in this example (although you should be able to confirm it by just looking at the VRAM usage). To make it so CUDA doesn't use system memory, you must ensure you have the Studio (not Game-Ready) Nvidia driver, then [change a setting in Nvidia Control Panel](https://nvidia.custhelp.com/app/answers/detail/a_id/5490/~/system-memory-fallback-for-stable-diffusion).

**Comment by dacorvo** [comment]
There is some code in the benchmark section that tracks CUDA device memory:

https://github.com/huggingface/quanto/blob/main/bench/generation/metrics/latency.py

```python
def get_device_memory(device):
    gc.collect()
    if device.type == "cuda":
        torch.cuda.empty_cache()
        return torch.cuda.memory_allocated()
    elif device.type == "mps":
        torch.mps.empty_cache()
        return torch.mps.current_allocated_memory()
    return None
```

Could you try to use that code and see what numbers are reported ?

**Comment by jonahclarsen** [comment]
> There is some code in the benchmark section that tracks device memory:
> 
> https://github.com/huggingface/quanto/blob/main/bench/generation/metrics/latency.py
> 
> ```python
> def get_device_memory(device):
>     gc.collect()
>     if device.type == "cuda":
>         torch.cuda.empty_cache()
>         return torch.cuda.memory_allocated()
>     elif device.type == "mps":
>         torch.mps.empty_cache()
>         return torch.mps.current_allocated_memory()
>     return None
> ```
> 
> Could you try to use that code and see what numbers are reported ?

Ran it a few times with that code with size=1500. 

With fp16: 2327326208
With qint8: 1473672704

This is odd though, since in Task Manager, GPU VRAM is the same in both cases.

Also, side note, I know this is probably expected, but inference is ~3x slower at qint8 than fp16.

**Comment by dacorvo** [comment]
> This is odd though, since in Task Manager, GPU VRAM is the same in both cases.

The measurement provided by pytorch is the one you should trust.

> Also, side note, I know this is probably expected, but inference is ~3x slower at qint8 than fp16.

Yes, the first public version of quanto does not integrate optimized kernels for mixed precision matrix multiplication, so this is expected. I am currently integrating kernels for fp16 x qint4, fp16x qint8 will be next.

**Comment by jonahclarsen** [comment]
> The measurement provided by pytorch is the one you should trust.

Do you have any idea where the discrepancy comes from? Because for my use case, it doesn't matter that that Pytorch _says_ less VRAM is being used, it's hitting the same ceiling as it is with fp16.

I want to be able to run larger images through VGG-19 than I can at fp16, but I can't fit any larger images through it with qint8 than with fp16 - in both cases, I get "CUDA out of memory error" at the same image size. I'm confused why Pytorch says less VRAM is being used with qint8 (while Task Manager disagrees), and why that doesn't translate into being able to inference it with larger images.

**Comment by dacorvo** [comment]
I see, my mistake: the numbers reported by pytorch are for quantized weights only, without any activations.
When you pass images through the model, large activation buffers are also allocated, and this is what you see in the Task Manager. 
You are using quantized activations, which is good, but there is a caveat: if some operations in the graph are not compatible with integer, the activations are converted back to float when reaching these operations.
quanto does not support int8/int8 convolutions yet, so always falls back to to float. This is probably what explains the extra VRAM.

**Comment by jonahclarsen** [comment]
Ah okay, that makes sense, thanks. Do you have an ETA on when qint8 or qint4 convolution CUDA kernels will be implemented?
