### ISSUE TITLE
Can I use quanto on AMD GPU?

### ISSUE THREAD

**Issue by catsled** [huggingface/quanto#182]
Does quanto work with AMD GPUs ?

**Comment by dacorvo** [comment]
quanto does not use very fancy CUDA kernels, so I don;t see any reason why it wouldn't work. Just give it a try and please report your feedback.

**Comment by catsled** [comment]
> quanto does not use very fancy CUDA kernels, so I don't see any reason why it wouldn't work. Just give it a try and please report your feedback.

ok, thanks i'll try ...
