### ISSUE TITLE
Got stuck when train resnet50 with QAT

### ISSUE THREAD

**Issue by catsled** [huggingface/quanto#183]
When I quantize a ResNet50 model and train it, it may get stuck at the first backward pass; it's normal when I train a non-quantized model..

GPU:A800
data:Cifar10

![image](https://github.com/huggingface/quanto/assets/18079717/e610a464-2b6d-4b39-8366-125bae2907cb)

![image](https://github.com/huggingface/quanto/assets/18079717/12d15dd0-f9aa-4d2d-857d-968fd7feb721)

how should i do?

**Comment by dacorvo** [comment]
It is strange that you get integer output. Did you take a look at the MNIST example ? If not, maybe compare with your script and see if something is different.

**Comment by catsled** [comment]
> It is strange that you get integer output. Did you take a look at the MNIST example ? If not, maybe compare with your script and see if something is different.

ok : )

**Comment by catsled** [comment]
got stuck when calibration(i did't add it before )
![image](https://github.com/huggingface/quanto/assets/18079717/8c1d50cb-daa3-4f3c-9b3e-d914fe7ec4e5)
![image](https://github.com/huggingface/quanto/assets/18079717/df9e164d-90da-43c1-b15d-d42df96b750a)

**Comment by dacorvo** [comment]
How long does it take to run evaluate on the float model ?

**Comment by catsled** [comment]
> How long does it take to run evaluate on the float model ?

about 8s

**Comment by LukeLIN-web** [comment]
> got stuck when calibration(i did't add it before ) ![image](https://private-user-images.githubusercontent.com/18079717/323872591-8c1d50cb-daa3-4f3c-9b3e-d914fe7ec4e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0NDEwODEsIm5iZiI6MTczNjQ0MDc4MSwicGF0aCI6Ii8xODA3OTcxNy8zMjM4NzI1OTEtOGMxZDUwY2ItZGFhMy00ZjNjLTliM2UtZDkxNGZlN2VjNGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA5VDE2Mzk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViZjEzOTk2ZjU3OTE5MzliOTRiYjlmYTE1NWQ4YmQyOTZjMjQ3MjQ1MjhhNzU2MTAwYTgwNGRmNTdiNjNiOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LWuIJqkO0ungXK6vKrUE0DBEVciU0HuUIUqaq_rMU2M) ![image](https://private-user-images.githubusercontent.com/18079717/323872468-df9e164d-90da-43c1-b15d-d42df96b750a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0NDEwODEsIm5iZiI6MTczNjQ0MDc4MSwicGF0aCI6Ii8xODA3OTcxNy8zMjM4NzI0NjgtZGY5ZTE2NGQtOTBkYS00M2MxLWIxNWQtZDQyZGY5NmI3NTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA5VDE2Mzk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwZGJhMTYxYzdiMDBjMmZlZjc3NWVlMGExNTI0MDdjZGYyNmI1Zjg2ZjM1ZDdjM2IwNTdiMjQ5YzU0NWRiNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jXOZp-p_97EPCEealCZ9Yp5ZTsRdgIDsVELtb2aBSCg)

Did you solve it? How did you compute  QAT  loss?
