### ISSUE TITLE
[Feature Request] INT16 🤗

### ISSUE THREAD

**Issue by duanshengliu** [huggingface/quanto#190]
First of all, I would like to express my gratitude to the developers of quanto for their great work. I have noticed that quanto have the following features:
- supports int2, int4, int8 and float8 weights,
- supports int8 and float8 activations.
I also noticed that for some small/tiny models like: [TinyLlama/TinyLlama-1.1B-Chat-v1.0](https://huggingface.co/TinyLlama/TinyLlama-1.1B-Chat-v1.0) , the precision of **int8/float8** is not enough. 
So Is there any plan to support **int16** weights and activations, thanks.

**Comment by dacorvo** [comment]
@duanshengliu there is no plan for supporting int16, as it does not provide any benefit over float16 for most hardware devices.
I assume you are interested in this to support NPUs without floating point arithmetics: this is unfortunately not in the scope of quanto.

**Comment by duanshengliu** [comment]
Thank you for your comments.
