### ISSUE TITLE
int8 matmul on x86 using with intel oneDnn

### ISSUE THREAD

**Issue by dacorvo** [huggingface/quanto#64]
It should be possible to accelerate the `int8` inference on CPU using something like the ATEN int8 OneDNN linear:

https://github.com/pytorch/pytorch/blob/7a6cb9fdfb01ab6e9ce55f1fb86348f1a6be8735/aten/src/ATen/native/quantized/cpu/qlinear.cpp#L909

**Comment by maktukmak** [comment]
Is there any update on this? toch._int_mm only has cuda backend. It would be great if we could choose the CPU backend for this op so that Quanto can run on the CPU as well.

**Comment by dacorvo** [comment]
quanto can run on cpu, but the matmul is done after promoting (casting) terms to float32 in that case.

**Comment by maktukmak** [comment]
Yes, it works by using FP32 gemms, which is slower as you said. Is there any work in progress to use int8 gemms instead?
