### ISSUE TITLE
Incompatible with torch.load(...,weights_only=True)

### ISSUE THREAD

**Issue by SunMarc** [huggingface/quanto#93]
Quanto tensors (e.g. `QTensor` ) + many other methods that are used in quanto (e.g. `torch.Tensor._make_wrapper_subclass`) are incompatible with `torch.load(...,weights_only=True)`. In transformers, we started using `weights_only=True` with this [PR](https://github.com/huggingface/transformers/pull/27282) to make pickle format a bit safer but it comes with less flexibility. When using `weights_only=True`, it will call this [function](https://github.com/pytorch/pytorch/blob/957f37686a3974df12612c448dbdc700ac861f41/torch/serialization.py#L1020) and you can have a look at how they perform the weights only unpickle in this [file](https://github.com/pytorch/pytorch/blob/957f37686a3974df12612c448dbdc700ac861f41/torch/_weights_only_unpickler.py#L4). 

I don't think we can manage to make it work easily. As an alternative, I will investigate if safetensors format can be easily compatible with quanto models.

cc @dacorvo @younesbelkada 

### Reproducer:
Replace 
```python
b = io.BytesIO()
torch.save(model.state_dict(), b)
b.seek(0)
state_dict = torch.load(b)
```
by 
```python 
torch.save(model.state_dict(), "model_quanto.bin")
state_dict = torch.load("model_quanto.bin", weights_only=True)
```
in the `test_serialization.py/test_serialize_quantized_mlp` test

**Comment by dacorvo** [comment]
Looking at the torch weight-only-pickler, it seems compatible with Tensor subclasses:

https://github.com/pytorch/pytorch/blob/8ac9b20d4b090c213799e81acf48a55ea8d437d6/torch/_weights_only_unpickler.py#L117

**Comment by dacorvo** [comment]
This is not easy to figure out how we could override the serialization logic to make `QTensor` compatible with `weights_only = True`.
However, it is possible to override the serialization logic of `QModuleMixin`, which should be enough for most use cases.
